title: ''
author: Quang Hung &#9829; Thuy Linh
logo: image/book/logo.svg
only_build_toc_files: true
exclude_patterns: [
  '_build',
  '.DS_Store',
  '**.ipynb_checkpoints',
  'README.md',
  'Thumbs.db',
  'util/refactor.ipynb'
]

execute:
  execute_notebooks: off # (auto, force, cache, off)

repository:
  url: https://github.com/hungpq7/tabular-book

html:
  favicon: image/book/favicon.ico
  use_issues_button: false
  use_repository_button: true
  use_download_button: false

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files: https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options:
      repository_url: https://github.com/hungpq7/tabular-book
      use_repository_button: true
      use_download_button: false
      launch_buttons:
        notebook_interface: jupyterlab # (classic, jupyterlab)
        binderhub_url: https://mybinder.org
        colab_url: https://colab.research.google.com
        thebe: true

launch_buttons:
  notebook_interface: jupyterlab # (classic, jupyterlab)
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  thebe: true

parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution